version: '3'

services:
  rafael-test-api:
    container_name: rafael-test-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - rafael-test-db
    volumes:
      - ./:/rafael-test-api

  rafael-test-db:
    container_name: rafael-test-db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    ports:
      - '5434:5432'
